<?php
$title = 'My albums';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
    <?php if($this->isAllowed('editor')) { ?>
    <a href="album/add">Add new album</a> <!--  < ?php echo $this->url('album', array('action'=>'add'));? > -->
    <?php } ?>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($albums as $album) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($album->title);?></td>
        <td><?php echo $this->escapeHtml($album->artist);?></td>
        <td>
            <?php if($this->isAllowed('editor')) { ?>
            <a href="album/edit/<?= $album->id; ?>">Edit</a>
            <!-- < ?php echo $this->url('album', array('action'=>'edit', 'id' => $album->id));? >  -->
            <?php } ?>
            <?php if($this->isAllowed('super')) { ?>
            <a href="<?php echo $this->url('album', array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
            <?php } ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>