<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SwebContact\Controller\ContactController'        => __DIR__ . '/src/SwebContact/Controller/ContactController.php',
    'SwebContact\Form\ContactForm'                    => __DIR__ . '/src/SwebContact/Form/ContactForm.php',
    'SwebContact\Service\ContactCaptchaFactory'       => __DIR__ . '/src/SwebContact/Service/ContactCaptchaFactory.php',
    'SwebContact\Service\ContactControllerFactory'    => __DIR__ . '/src/SwebContact/Service/ContactControllerFactory.php',
    'SwebContact\Service\ContactFormFactory'          => __DIR__ . '/src/SwebContact/Service/ContactFormFactory.php',
    'SwebContact\Service\ContactMailMessageFactory'   => __DIR__ . '/src/SwebContact/Service/ContactMailMessageFactory.php',
    'SwebContact\Service\ContactMailTransportFactory' => __DIR__ . '/src/SwebContact/Service/ContactMailTransportFactory.php',
);